# Change these first
owner: carlostkd # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: carlostkd
    url: $SOPHIE
  - name: Recognizing People 
    url: $RECOGNIZING_PEOPLE
  - name: sophie
    url: $AI
  - name: Keys
    url: $KEYS
  - name: STORAGE
    url: $STORAGE
  - name: Mobile
    url: $MOBILE
  - name: Teams
    url: $TEAMS

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: carlostkd.ch
  baseUrl: /status
  logoUrl: $LOGO
  name: Sophie AI Status
  introTitle: "**Sophie Status** is the uptime monitor and status page."
  introMessage: Status Page
  navbar:
    - title: Status
      href: /status
    - title: Sophie
      href: https://carlostkd.ch/sophie

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
