# Sophie Powered AI Monitor
status-website:
  theme: dark
owner: carlostkd # Sophie AI is powered by carlostkd
repo: status 

sites:
  - name: carlostkd
    url: $SOPHIE
  - name: Recognizing People 
    url: $RECOGNIZING_PEOPLE
  - name: sophie
    url: $AI
  - name: Keys
    url: $KEYS
  - name: STORAGE
    url: $STORAGE
  - name: Mobile
    url: $MOBILE
  - name: Teams
    url: $TEAMS
  - name: DNS
    check: "tcp-ping"
    url: $DNS
    port: $DNS_PORT

status-website:
  
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/carlostkd/status/master/assets/ai-favicon.png
  name: Sophie AI Status
  introTitle: "**Sophie Status** is the uptime monitor and status page."
  introMessage: Status Page
  navbar:
    - title: Status
      href: /status
    - title: Sophie
      href: https://carlostkd.ch/sophie



