# Change these first
owner: carlostkd # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: carlostkd
    url: https://carlostkd.ch
  - name: sophie
    url: https://carlostkd.ch/sophie
  - name: Keys
    url: https://carlostkd.ch/cloud/search.php
  - name: AI
    url: https://carlostkd.ch/AI

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: carlostkd.ch
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sophie AI Status
  introTitle: "**Sophie Status** is the uptime monitor and status page."
  introMessage: Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/carlostkd/status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
